# Deployment do conversão de temperatura
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  selector:
    matchLabels:
      app: conv
  template:
    metadata:
      name: convpod
      labels:
        app: conv
    spec:
      containers:
        - name: conv
          image: ymritchie/conversao-temperatura-curso:v1
          ports:
            - containerPort: 8080 
---

apiVersion: v1
kind: Service
metadata:
  name: conv
spec:
  selector:
    app: conv
  ports:
    - port: 8080
      nodePort: 30000
  type: LoadBalancer 